apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  # Note Grafana will do calls from the frontend! So don't change this to the docker host name!
  url: http://prometheus:9090
  isDefault: true